apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  version: v2.6
  tracing:
    type: Jaeger
  kiali:
    enabled: true
  prometheus:
    enabled: true
