apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtual-service-food
  namespace: group-4
spec:
  hosts:
  - recommendations
  - payments
  http:
    - route:
        - destination:
            host: recommendations
            subset: recommendation-food  # recommendations 的子集
            port:
              number: 8080
          weight: 20
        - destination:
            host: payments  # payments 没有子集，直接指向主版本
            port:
              number: 8080
          weight: 80